name: test-build-release

on: [ push ]

jobs:

  tests-sca:
    uses: maikschneider/reusable-workflows/.github/workflows/sca.yml@main
    with:
      php-version: 8.1

  release:
    if: github.ref == 'refs/heads/development'
    needs:
      - tests-sca
    uses: maikschneider/reusable-workflows/.github/workflows/release-typo3-extension.yml@main
    secrets:
      teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
    with:
      base-branch: master
      publish-ter: true
